version: "1.0"

volumes:
  habolabu_client_data:

services:
  habolabu_client:
    container_name: "habolabu-client"
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    ports:
      - ${PORT}:${CLIENT_CONTAINER_PORT}
    volumes:
      - habolabu_client_data:${HABOLABU_CLIENT_VOLUMES}
    env_file:
      - .env
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
  nginx_server:
    container_name: "nginx-server"
    image: nginx:1.23.4
    ports:
      - ${NGINX_HOST_POST}:${NGINX_CONTAINER_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    restart: unless-stopped
